linters-settings:
  errcheck:
    exclude: .errcheck.txt
linters:
  disable-all: true
  enable:
  - deadcode
  - errcheck
  - gofmt
  - goimports
  - gosec
  - gocritic
  - golint
  - misspell
output:
  uniq-by-line: false
issues:
  exclude-rules:
  - path: _test\.go
    linters:
    - errcheck
    - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
run:
  issues-exit-code: 1
  build-tags:
  - e2e
  skip-files:
  - .*/zz_generated.deepcopy.go
  skip-dirs:
  - vendor
  - pkg/client
  timeout: 10m
  modules-download-mode: vendor
