apiVersion: tekton.dev/v1alpha1
kind: ClusterTask
metadata:
  name: clustertask-v1alpha1
spec:
  steps:
  - image: ubuntu
    script: echo hello
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: clustertask-
spec:
  taskRef:
    name: clustertask-v1alpha1
    kind: ClusterTask
